name: Build & Upload to Firebase App Distribution

on:
  push:
    branches:
      - develop
      - main

env:
  JAVA_VERSION: '12.x'
  FLUTTER_VERSION: '3.3.10'
  FIREBASE_TESTERS_GROUPS: 'Testers'

  # Android
  APK_NAME: app-prod-release.apk
  APK_PATH: build/app/outputs/flutter-apk/app-prod-release.apk

  # iOS

  # secrets
  # FIREBASE_TOKEN
  # GOOGLE_SERVICES
  # GOOGLE_SERVICE_INFO
  # ENVIRONMENT
  # ANDROID_APP_ID

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: echo "$GOOGLE_SERVICES" > android/app/google-services.json
      - name: Decode GoogleService-Info.plist
        env:
          GOOGLE_SERVICE_INFO: ${{ secrets.GOOGLE_SERVICE_INFO }}
        run: echo "$GOOGLE_SERVICE_INFO" > ios/Runner/GoogleService-Info.plist
      - name: Decode .env
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: echo "$ENVIRONMENT" > .env

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: make build-apk ENV=prod
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APK_NAME }}
          path: ${{ env.APK_PATH }}
          retention-days: 1
          if-no-files-found: error

  distribute-android:
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{ env.APK_NAME }}

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: ${{ env.FIREBASE_TESTERS_GROUPS }}
          file: ${{env.APK_NAME}}
          releaseNotes: '${{ github.event.head_commit.author.name }}: ${{ github.event.head_commit.message }}'
